### ISSUE TITLE
java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by MunirAhmad** [adamrocker/simple-side-drawer#14]
Hi, I am using simple-side-drawer with fragment, first time its render contents but after pop fragment, when I again render that fragment that I have pop,  its give me exception. you can see that exception below 

 `

 syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
 E/UncaughtException: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
        at com.navdrawer.SimpleSideDrawer.<init>(SimpleSideDrawer.java:240)
        at com.navdrawer.SimpleSideDrawer.<init>(SimpleSideDrawer.java:193)
        at browseactivitiesreeboks.BrowseActivitiesByCatagoryActivity.setUpViews(BrowseActivitiesByCatagoryActivity.java:127)
        at browseactivitiesreeboks.BrowseActivitiesByCatagoryActivity.onCreateView(BrowseActivitiesByCatagoryActivity.java:104)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

throwable java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.istar.reebok.reeboks, PID: 2011
java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
    at com.navdrawer.SimpleSideDrawer.<init>(SimpleSideDrawer.java:240)
    at com.navdrawer.SimpleSideDrawer.<init>(SimpleSideDrawer.java:193)
    at browseactivitiesreeboks.BrowseActivitiesByCatagoryActivity.setUpViews(BrowseActivitiesByCatagoryActivity.java:127)
    at browseactivitiesreeboks.BrowseActivitiesByCatagoryActivity.onCreateView(BrowseActivitiesByCatagoryActivity.java:104)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

how to handle that exception, please help me 

Regards 
Munir Ahmad

**Comment by adamrocker** [comment]
Could you please let me know the actual instance type at SimpleSideDrawer#240.
https://github.com/adamrocker/simple-side-drawer/blob/master/SimpleSideDrawer/src/com/navdrawer/SimpleSideDrawer.java#L240

**Comment by MunirAhmad** [comment]
here is the code to create instance 

`SimpleSideDrawer slide_me = new SimpleSideDrawer(getActivity());
slide_me.setRightBehindContentView(R.layout.browse_activities_filter_by_activity);`

XML of layout that is used for 
slide_me.setRightBehindContentView(R.layout.browse_activities_filter_by_activity);

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"

```
android:layout_width="@dimen/browser_width"
android:layout_height="match_parent"
android:background="@color/off_white"
android:orientation="vertical">

<LinearLayout
    android:id="@+id/browse_activities_filterby_ll_title"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentTop="true"
    android:orientation="vertical">

    <TextView
        android:id="@+id/browse_activities_filterby_filter"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/bg"
        android:paddingBottom="@dimen/margin_larger"
        android:paddingLeft="@dimen/margin_35"
        android:paddingTop="@dimen/margin_larger"
        android:text="Filter By"
        android:textAllCaps="true"
        android:textColor="@color/dark_color"
        android:textSize="@dimen/txt_larger" />

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/myWindowBackground" />
</LinearLayout>

<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_above="@+id/browse_activities_filterby_ll_footer"
    android:layout_below="@+id/browse_activities_filterby_ll_title"
    android:orientation="vertical">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view_filterby"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</LinearLayout>

<LinearLayout
    android:id="@+id/browse_activities_filterby_ll_footer"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentBottom="true"
    android:layout_marginBottom="@dimen/margin_normal"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/margin_larger"
        android:background="@drawable/dark_orange_bg"
        android:orientation="vertical">

        <Button
            android:id="@+id/browse_activities_btn_resetfilter"
            style="@style/Base.Widget.AppCompat.Button.Borderless"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="Reset filters"
            android:textColor="@android:color/white"
            android:textSize="@dimen/txt_larger" />
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="@dimen/margin_larger"
        android:layout_marginRight="@dimen/margin_larger"
        android:background="@drawable/green_light_bg"
        android:orientation="vertical">

        <Button
            android:id="@+id/browse_activities_btn_applyfilter"
            style="@style/Base.Widget.AppCompat.Button.Borderless"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="apply filters"
            android:textColor="@android:color/white"
            android:textSize="@dimen/txt_larger" />
    </LinearLayout>

</LinearLayout>
```

</LinearLayout>`

here I am provide the detail of code line 240  debugging

[https://dl.dropboxusercontent.com/u/81628682/Exception/SlideChild.png](url)
[https://dl.dropboxusercontent.com/u/81628682/Exception/Slide.png](url)

**Comment by MunirAhmad** [comment]
for reference 
I upload for detail to examine error 
![slidechild](https://cloud.githubusercontent.com/assets/10996366/17695220/fdac5a8a-63c0-11e6-9603-1c0fb81f4dbe.png)

![slide](https://cloud.githubusercontent.com/assets/10996366/17695243/2107717c-63c1-11e6-9603-d20aff7ea9f2.png)

**Comment by MunirAhmad** [comment]
@adamrocker

**Comment by MunirAhmad** [comment]
I have solve it 

` ViewGroup decor = (ViewGroup) mWindow.getDecorView();
        View above =  decor.getChildAt(0);//including actionbar
        decor.removeView(above);
        mAboveView.addView(above);

I am not casting that line of code `ViewGroup above = (ViewGroup) decor.getChildAt(0);`
I have change that line into `View above =  decor.getChildAt(0);`
Also comment these two line 
`above.setBackgroundDrawable(decor.getBackground());
mAboveView.addView(mOverlay);` 
first line changes color of device action bar and 2nd line add overly to my current UI`
Now there is no issue with its, render properly  

Regards

Munir Ahmad
